# Site settings
title:          大尾巴鱼
description:    "个人博客网站"
baseurl:        ""
url:            "https://daweibayu.fun"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         daweibayu
  url:          https://daweibayu.fun
  email:        daweibayu@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       15

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale